Nom : Tests PHPUnit

sur : [push, pull_request]

emplois :
  tests :
    fonctionne sous : ubuntu-latest
    
    étapes :
    - utilise : actions/checkout@v4
    
    - nom : Configuration PHP
      utilise : shivammathur/setup-php@v2
      avec :
        version PHP : '8.2'
    
    - nom : Installer les dépendances
      run : composer install --prefer-dist --no-progress --no-suggest
    
    - nom : Donner les permissions d'exécution
      run : chmod +x vendor/bin/phpunit
    
    - nom : Exécuter les tests PHPUnit
      run : vendor/bin/phpunit --testdox
